from .dashboard import dashboard_blueprint
from .notes import notes_blueprint
from .transcribe import transcribe_blueprint
from .chatbot import chatbot_blueprint
from .quiz import quiz_blueprint
from .flashcards import flashcards_blueprint
from .podcast import podcast_blueprint
from .auth import auth_blueprint
from .errors import error_blueprint
